In [1]:
import numpy as np

# Ejercicios Pair Programming - Módulo 2 Sprint 1
## Lección 3 - Numpy IV
### Noemi Azorin y Silvia Gordón

1 - ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [8]:
np.random.seed(1)
arr1 = np.random.random_sample((3,6))
arr1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01, 5.38816734e-01,
        4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01,
        4.17304802e-01, 5.58689828e-01]])

In [9]:
np.random.seed(1)
arr2 = np.random.random_sample((3,6))
arr2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01, 5.38816734e-01,
        4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01,
        4.17304802e-01, 5.58689828e-01]])

2 - Cread los siguientes arrays:

- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [10]:
arr3 = np.round(np.random.uniform(0,10, size = (2,3,5)))
arr3

array([[[ 1.,  2.,  8., 10.,  3.],
        [ 7.,  9.,  9.,  1.,  0.],
        [ 2.,  9.,  1.,  4., 10.]],

       [[ 5.,  7.,  3.,  7.,  8.],
        [ 0.,  8., 10.,  7.,  3.],
        [ 8.,  1.,  4.,  9.,  3.]]])

In [11]:
unicos_uniform = np.unique(arr3)
unicos_uniform

array([ 0.,  1.,  2.,  3.,  4.,  5.,  7.,  8.,  9., 10.])

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [12]:
arr4 = np.random.binomial(10, 0.3, size = (2,3,5))
arr4

array([[[2, 1, 0, 4, 2],
        [2, 3, 1, 3, 1],
        [3, 4, 1, 3, 4]],

       [[3, 1, 3, 4, 3],
        [5, 3, 5, 1, 1],
        [4, 3, 2, 5, 2]]])

In [13]:
unicos_binomial = np.unique(arr4)
unicos_binomial

array([0, 1, 2, 3, 4, 5])

3 - En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
- Elementos comunes entre los dos arrays

In [14]:
comunes = np.intersect1d(unicos_uniform, unicos_binomial)
comunes

array([0., 1., 2., 3., 4., 5.])

- Unión de los dos arrays

In [15]:
union = np.union1d(unicos_uniform, unicos_binomial)
union

array([ 0.,  1.,  2.,  3.,  4.,  5.,  7.,  8.,  9., 10.])

- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [16]:
diff = np.setdiff1d(unicos_uniform, unicos_binomial)
diff

array([ 7.,  8.,  9., 10.])

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

- El método intersect1d nos devuelve los elementos comunes de ambos arrays.
- El método union1d nos devuelve la unión de los dos arrays.
- El método setdiff1d nos devuelve los valores únicos de uniform que no están en binomial.

4 - Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [18]:
array1 = np.random.randint(1,100, (80))
array1

array([83, 97, 14, 11, 24, 82,  8, 25, 75, 93, 21, 33, 13, 66, 95, 61, 25,
       83, 98,  3, 93, 99, 11, 55, 97, 83, 87, 71, 67, 72, 49, 55, 16,  6,
       18, 43, 21, 49, 23, 14, 98, 54, 85, 11, 97, 56, 62, 57, 90, 22, 97,
       84, 26, 15, 14, 85, 44,  7, 78, 57, 60, 16, 25, 10, 67, 72, 54, 70,
       37, 22, 41, 78, 92, 50, 48, 78, 41, 79, 46, 88])

In [19]:
array2 = np.random.randint(1,100, (80))
array2

array([17, 29, 46, 68, 67, 79, 47,  1, 30, 64, 76, 36, 54, 94, 34,  3, 85,
       84, 49, 55, 33, 29, 56, 83, 32, 29, 95, 75,  9, 33,  9, 85, 78, 51,
       80, 42, 65, 84, 25, 21, 45, 16, 31, 92, 15, 20, 27, 87,  8, 54, 48,
       61, 35, 33, 20, 68, 25, 84, 95, 39, 48,  6, 80, 64, 88, 33, 43, 75,
       67, 89, 99, 31, 18, 69, 65, 61, 79, 18, 40, 36])

 - Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [20]:
array1 = np.unique(array1)
array1

array([ 3,  6,  7,  8, 10, 11, 13, 14, 15, 16, 18, 21, 22, 23, 24, 25, 26,
       33, 37, 41, 43, 44, 46, 48, 49, 50, 54, 55, 56, 57, 60, 61, 62, 66,
       67, 70, 71, 72, 75, 78, 79, 82, 83, 84, 85, 87, 88, 90, 92, 93, 95,
       97, 98, 99])

In [21]:
array2 = np.unique(array2)
array2

array([ 1,  3,  6,  8,  9, 15, 16, 17, 18, 20, 21, 25, 27, 29, 30, 31, 32,
       33, 34, 35, 36, 39, 40, 42, 43, 45, 46, 47, 48, 49, 51, 54, 55, 56,
       61, 64, 65, 67, 68, 69, 75, 76, 78, 79, 80, 83, 84, 85, 87, 88, 89,
       92, 94, 95, 99])

- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [22]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 7, 10, 11, 13, 14, 22, 23, 24, 26, 37, 41, 44, 50, 57, 60, 62, 66,
       70, 71, 72, 82, 90, 93, 97, 98])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [23]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 1,  9, 17, 20, 27, 29, 30, 31, 32, 34, 35, 36, 39, 40, 42, 45, 47,
       51, 64, 65, 68, 69, 76, 80, 89, 94])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [24]:
array5 = np.intersect1d(array1, array2)
array5

array([ 3,  6,  8, 15, 16, 18, 21, 25, 33, 43, 46, 48, 49, 54, 55, 56, 61,
       67, 75, 78, 79, 83, 84, 85, 87, 88, 92, 95, 99])

- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [25]:
len(array3)

25

In [26]:
len(array4)

26

In [27]:
len(array5)

29

- El método setdiff1d para el array3 nos ha devuelto los elementos presentes en el array1 que no están en el array2. 
Nos da una longitud de 25 elementos.
- El método setdiff1d para el array4 nos ha devuelto los elementos presentes en el array2 que no están en el array1. 
Nos da una longitud de 26 elementos.
- El método insersect1d para el array5 nos ha devuelto los elementos comunes de ambos arrays. 
Nos da una longitud de 29 elementos.
- Todas los elementos resultantes de aplicar los métodos mencionados anteriormente son distintos entre sí.
- La suma de la longitud de los tres arrays, nos devuelve el total de 80 elementos que tienen la misma forma que los arrays creados con el método random.randint.