# Ejercicios Pair Programming - Módulo 2 Sprint 1
## Lección 1 - Numpy I - Introducción a Numpy
### Noemi Azorin y Silvia Gordón

En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.

In [1]:
import numpy as np

1.- Cread tres arrays: de una, dos y tres dimensiones.

Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
📌 Nota

El array de 2 dimensiones debe ser de 2 filas y 3 columnas

El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [2]:
array1 = np.random.randint(0,100, (1))
array1

array([99])

In [3]:
array2 = np.random.randint(0,100, (2,3))
array2

array([[47,  4, 34],
       [50,  3, 56]])

In [4]:
array3 = np.random.randint(0,100, (2,3,5))
array3

array([[[21, 82, 33,  5, 85],
        [70, 39, 57, 39, 83],
        [ 8, 95, 38, 16, 75]],

       [[70, 41, 55, 91, 96],
        [94, 35,  8, 52, 46],
        [15, 34, 91, 40, 36]]])

2.- Chequead las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [5]:
def propiedades_array(array):
    print(f"La forma de este array: {array} es: {array.shape}")
    print(f"La dimensión de este array: {array} es: {array.ndim}")
    print(f"El tamaño de este array: {array} es: {array.size}")
    print(f"El tipo de datos de este array: {array} es: {array.dtype}")

In [6]:
# Llamada a la función para el array1
propiedades_array(array1)

La forma de este array: [99] es: (1,)
La dimensión de este array: [99] es: 1
El tamaño de este array: [99] es: 1
El tipo de datos de este array: [99] es: int64


In [7]:
# Llamada a la función para el array2
propiedades_array(array2)

La forma de este array: [[47  4 34]
 [50  3 56]] es: (2, 3)
La dimensión de este array: [[47  4 34]
 [50  3 56]] es: 2
El tamaño de este array: [[47  4 34]
 [50  3 56]] es: 6
El tipo de datos de este array: [[47  4 34]
 [50  3 56]] es: int64


In [8]:
# Llamada a la función para el array3
propiedades_array(array3)

La forma de este array: [[[21 82 33  5 85]
  [70 39 57 39 83]
  [ 8 95 38 16 75]]

 [[70 41 55 91 96]
  [94 35  8 52 46]
  [15 34 91 40 36]]] es: (2, 3, 5)
La dimensión de este array: [[[21 82 33  5 85]
  [70 39 57 39 83]
  [ 8 95 38 16 75]]

 [[70 41 55 91 96]
  [94 35  8 52 46]
  [15 34 91 40 36]]] es: 3
El tamaño de este array: [[[21 82 33  5 85]
  [70 39 57 39 83]
  [ 8 95 38 16 75]]

 [[70 41 55 91 96]
  [94 35  8 52 46]
  [15 34 91 40 36]]] es: 30
El tipo de datos de este array: [[[21 82 33  5 85]
  [70 39 57 39 83]
  [ 8 95 38 16 75]]

 [[70 41 55 91 96]
  [94 35  8 52 46]
  [15 34 91 40 36]]] es: int64


3.- Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [13]:
matriz_identidad = np.identity(3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4.- Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [11]:
matriz_unos = np.ones_like(array3)
matriz_unos

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5.- Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

No, porque tiene que tener el mismo número de filas y columnas

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [14]:
matriz_identidad2= np.identity(3)
matriz_identidad2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
matriz_identidad_suma = np.add(matriz_identidad,matriz_identidad2)
matriz_identidad_suma

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [20]:
matriz_identidad_multiplicacion = np.multiply(matriz_identidad,matriz_identidad_suma)
matriz_identidad_multiplicacion

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

Dividid las dos matricess

In [23]:
matriz_identidad_division = np.divide(matriz_identidad,matriz_identidad_suma)
matriz_identidad_division

# La división entre las matrices me devuelve solo el resultado de la diagonal que es donde hay valores
# con los que se puede operar.

/tmp/ipykernel_216/3817947262.py:1: RuntimeWarning: invalid value encountered in divide
  matriz_identidad_division = np.divide(matriz_identidad,matriz_identidad_suma)


array([[0.5, nan, nan],
       [nan, 0.5, nan],
       [nan, nan, 0.5]])