In [1]:
import numpy as np

# Ejercicios Pair Programming - Módulo 2 Sprint 1
## Lección 3 - Numpy III
### Noemi Azorin y Silvia Gordón

En esta lección hemos aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.

1.- Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [2]:
array1 = np.random.rand(2,3,5)
array1

array([[[0.35683279, 0.82852366, 0.0871282 , 0.66430834, 0.93817509],
        [0.75080765, 0.57328837, 0.10572106, 0.91740083, 0.7618409 ],
        [0.68431768, 0.10899114, 0.78522461, 0.71805323, 0.40286003]],

       [[0.28928881, 0.45361226, 0.56614227, 0.34149525, 0.96749853],
        [0.3498442 , 0.87764997, 0.71714796, 0.05621677, 0.48122878],
        [0.51009615, 0.26089278, 0.7610507 , 0.31723764, 0.81912945]]])

In [3]:
array1_redondeo = np.round(array1, decimals=1)
array1_redondeo

array([[[0.4, 0.8, 0.1, 0.7, 0.9],
        [0.8, 0.6, 0.1, 0.9, 0.8],
        [0.7, 0.1, 0.8, 0.7, 0.4]],

       [[0.3, 0.5, 0.6, 0.3, 1. ],
        [0.3, 0.9, 0.7, 0.1, 0.5],
        [0.5, 0.3, 0.8, 0.3, 0.8]]])

2.- Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [7]:
media = np.round(np.mean(array1_redondeo),1)
media

0.6

3.- Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [8]:
maximo = np.round(np.max(array1_redondeo),1)
maximo

1.0

4.- Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [9]:
minimo = np.round(np.min(array1_redondeo),1)
minimo

0.1

5.- Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [11]:
# Creamos un array vacio de tipo String para ir reemplanzdo los valores del array orginal a este array.

array_vacio = np.empty((2,3,5), dtype=str)
array_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [21]:
# Vamos a iterar por cada fila del array original y con el método any comprobamos si algún elemento cumple
# las condiciones que le pasemos. Si las cumple, en el array vacío lo reemplazaremos por la letra.

for a in array1_redondeo:
    if np.any(array1_redondeo == media):
        array_vacio[array1_redondeo == media] = "A"
    elif np.any(array1_redondeo > media):
        array_vacio[array1_redondeo > media] = "B"
    elif np.any(array1_redondeo < media):
        array_vacio[array1_redondeo < media] = "C"
    elif np.any(array1_redondeo == maximo):
        array_vacio[array1_redondeo == maximo] = "D"
    elif np.any(array1_redondeo == minimo):
        array_vacio[array1_redondeo == minimo] = "E"

In [22]:
# Mostramos el array original

array1_redondeo

array([[[0.4, 0.8, 0.1, 0.7, 0.9],
        [0.8, 0.6, 0.1, 0.9, 0.8],
        [0.7, 0.1, 0.8, 0.7, 0.4]],

       [[0.3, 0.5, 0.6, 0.3, 1. ],
        [0.3, 0.9, 0.7, 0.1, 0.5],
        [0.5, 0.3, 0.8, 0.3, 0.8]]])

In [23]:
# Mostramos el array con las letras que han reemplazado los valores.

array_vacio

array([[['C', 'B', 'E', 'B', 'B'],
        ['B', 'A', 'E', 'B', 'B'],
        ['B', 'E', 'B', 'B', 'C']],

       [['C', 'C', 'A', 'C', 'D'],
        ['C', 'B', 'B', 'E', 'C'],
        ['C', 'C', 'B', 'C', 'B']]], dtype='<U1')

6.- Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.

In [15]:
# Creamos un array vacío con 30 elementos.

array_vacio2 = np.empty(30)
array_vacio2

array([0.4, 0.8, 0.1, 0.7, 0.9, 0.8, 0.6, 0.1, 0.9, 0.8, 0.7, 0.1, 0.8,
       0.7, 0.4, 0.3, 0.5, 0.6, 0.3, 1. , 0.3, 0.9, 0.7, 0.1, 0.5, 0.5,
       0.3, 0.8, 0.3, 0.8])

Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1

Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2

Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [17]:
# Convertimos la dimensión de nuestro array de letras para que tenga la misma forma que el nuevo array.
# Los dos ahora serán unidimensionales.

array_vacio_letras = np.reshape(array_vacio, 30)
array_vacio_letras

array(['C', 'B', 'E', 'B', 'B', 'B', 'A', 'E', 'B', 'B', 'B', 'E', 'B',
       'B', 'C', 'C', 'C', 'A', 'C', 'D', 'C', 'B', 'B', 'E', 'C', 'C',
       'C', 'B', 'C', 'B'], dtype='<U1')

In [24]:
# Vamos a iterar por cada fila del array de letras y con el método any comprobamos si algún elemento cumple
# las condiciones que le pasemos. Si las cumple, en el array vacío lo reemplazaremos por el número.

for a in array_vacio_letras:
    if np.any(array_vacio_letras == "A") | np.any(array_vacio_letras == "B"):
        array_vacio2[(array_vacio_letras == "A") | (array_vacio_letras == "B")] = 1 
    elif np.any(array_vacio_letras == "C") | np.any(array_vacio_letras == "D"):
        array_vacio2[(array_vacio_letras == "C") | (array_vacio_letras == "D")] = 2
    elif np.any(array_vacio_letras == "E"):
        array_vacio2[array_vacio_letras == "E"] = 3 

In [25]:
# Mostramos el array vacío unidimensional con los elementos sustituidos.

array_vacio2

array([2., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 3., 1., 1., 2., 2., 2.,
       1., 2., 2., 2., 1., 1., 3., 2., 2., 2., 1., 2., 1.])

Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [26]:
# Cambiamos la forma de nuestro array unidimensional a multidimensional.

array_vacio3 = np.reshape(array_vacio2, (2,3,5))
array_vacio3

array([[[2., 1., 3., 1., 1.],
        [1., 1., 3., 1., 1.],
        [1., 3., 1., 1., 2.]],

       [[2., 2., 1., 2., 2.],
        [2., 1., 1., 3., 2.],
        [2., 2., 1., 2., 1.]]])

Happy coding 😀