# Ejercicios Pair Programming - Módulo 2 Sprint 1
## Lección 2 - Numpy II - Indexación
### Noemi Azorin y Silvia Gordón

Seguimos trabajando con NumPy, en este caso practicaremos como acceder a distintos elementos de nuestros arrays y como cambiar su forma para poder hacer operaciones entre varios arrays.

1 - Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:

In [1]:
import numpy as np

In [2]:
array = np.random.randint(0,10,(5,3))
array

array([[0, 6, 2],
       [7, 5, 5],
       [9, 8, 3],
       [1, 1, 3],
       [0, 2, 9]])

- El valor de la primera fila y la segunda columna.

In [3]:
array[0,1]

6

- Los valores de la segunda fila y las dos primeras columnas.

In [4]:
array[1,0:2]

array([7, 5])

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [10]:
array[::2]

array([[0, 6, 2],
       [9, 8, 3],
       [0, 2, 9]])

- Extraed los valores que sean mayores que 0.5.

In [11]:
array[array > 0.5]

array([6, 2, 7, 5, 5, 9, 8, 3, 1, 1, 3, 2, 9])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [12]:
array[(array < 0.2) | (array > 0.5)]

array([0, 6, 2, 7, 5, 5, 9, 8, 3, 1, 1, 3, 0, 2, 9])

2 - Cread dos array de tres dimensiones:
- El primero de 2 matrices, 5 filas y 3 columnas.

In [14]:
array1 = np.random.randint(0,10, (2,5,3))
array1

array([[[3, 1, 1],
        [3, 8, 5],
        [4, 0, 0],
        [8, 9, 8],
        [5, 0, 4]],

       [[2, 8, 0],
        [4, 0, 0],
        [7, 7, 7],
        [2, 9, 9],
        [0, 1, 2]]])

- El segundo de 3 matrices, 2 filas y 5 columnas

In [15]:
array2 = np.random.randint(0,10, (3,2,5))
array2

array([[[5, 2, 4, 6, 6],
        [3, 0, 6, 5, 6]],

       [[9, 4, 6, 7, 5],
        [6, 2, 1, 4, 4]],

       [[2, 0, 4, 5, 7],
        [7, 4, 0, 8, 5]]])

- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [16]:
def propiedades_array(array):
    print(f"La forma de este array: {array} es: {array.shape}")
    print(f"La dimensión de este array: {array} es: {array.ndim}")
    print(f"El tamaño de este array: {array} es: {array.size}")
    print(f"El tipo de datos de este array: {array} es: {array.dtype}")

In [17]:
propiedades_array(array1)

La forma de este array: [[[3 1 1]
  [3 8 5]
  [4 0 0]
  [8 9 8]
  [5 0 4]]

 [[2 8 0]
  [4 0 0]
  [7 7 7]
  [2 9 9]
  [0 1 2]]] es: (2, 5, 3)
La dimensión de este array: [[[3 1 1]
  [3 8 5]
  [4 0 0]
  [8 9 8]
  [5 0 4]]

 [[2 8 0]
  [4 0 0]
  [7 7 7]
  [2 9 9]
  [0 1 2]]] es: 3
El tamaño de este array: [[[3 1 1]
  [3 8 5]
  [4 0 0]
  [8 9 8]
  [5 0 4]]

 [[2 8 0]
  [4 0 0]
  [7 7 7]
  [2 9 9]
  [0 1 2]]] es: 30
El tipo de datos de este array: [[[3 1 1]
  [3 8 5]
  [4 0 0]
  [8 9 8]
  [5 0 4]]

 [[2 8 0]
  [4 0 0]
  [7 7 7]
  [2 9 9]
  [0 1 2]]] es: int32


In [18]:
propiedades_array(array2)

La forma de este array: [[[5 2 4 6 6]
  [3 0 6 5 6]]

 [[9 4 6 7 5]
  [6 2 1 4 4]]

 [[2 0 4 5 7]
  [7 4 0 8 5]]] es: (3, 2, 5)
La dimensión de este array: [[[5 2 4 6 6]
  [3 0 6 5 6]]

 [[9 4 6 7 5]
  [6 2 1 4 4]]

 [[2 0 4 5 7]
  [7 4 0 8 5]]] es: 3
El tamaño de este array: [[[5 2 4 6 6]
  [3 0 6 5 6]]

 [[9 4 6 7 5]
  [6 2 1 4 4]]

 [[2 0 4 5 7]
  [7 4 0 8 5]]] es: 30
El tipo de datos de este array: [[[5 2 4 6 6]
  [3 0 6 5 6]]

 [[9 4 6 7 5]
  [6 2 1 4 4]]

 [[2 0 4 5 7]
  [7 4 0 8 5]]] es: int32


- Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [19]:
#intento de suma de los dos arrays creados anteriormente
array_suma = array1 + array2
array_suma

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

Como podemos observar, no podemos sumar los arrays, ya que presentan distintas matrices.

- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
    .reshape()
    .transpose()
- Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [22]:
#intentamos modificar una matriz para poder sumar. 
#Utilizamos primero el método .reshape():

intento_reshape = np.reshape(array1,(3,2,5))
intento_reshape

array([[[3, 1, 1, 3, 8],
        [5, 4, 0, 0, 8]],

       [[9, 8, 5, 0, 4],
        [2, 8, 0, 4, 0]],

       [[0, 7, 7, 7, 2],
        [9, 9, 0, 1, 2]]])

In [23]:
#ahora procedemos a la suma:
array_suma2 = array2 + intento_reshape
array_suma2

array([[[ 8,  3,  5,  9, 14],
        [ 8,  4,  6,  5, 14]],

       [[18, 12, 11,  7,  9],
        [ 8, 10,  1,  8,  4]],

       [[ 2,  7, 11, 12,  9],
        [16, 13,  0,  9,  7]]])

In [24]:
#intentamos modificar la matriz con el método .transpose()
intento_transpose = np.transpose(array1,(2,0,1))
intento_transpose

array([[[3, 3, 4, 8, 5],
        [2, 4, 7, 2, 0]],

       [[1, 8, 0, 9, 0],
        [8, 0, 7, 9, 1]],

       [[1, 5, 0, 8, 4],
        [0, 0, 7, 9, 2]]])

In [25]:
#intentamos sumar después de haber modificado la matriz de nuevo:
suma_array3 = intento_transpose + array2
suma_array3

array([[[ 8,  5,  8, 14, 11],
        [ 5,  4, 13,  7,  6]],

       [[10, 12,  6, 16,  5],
        [14,  2,  8, 13,  5]],

       [[ 3,  5,  4, 13, 11],
        [ 7,  4,  7, 17,  7]]])